# This file was generated by GoReleaser. DO NOT EDIT.
cask "brooom" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "b5806801fbfc30720f52652d48b046cc38993abb024a8c5df72c24e368fe6c72"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1b7ea7821350600afc029c2fea50d02de5a6662ae61dff9e39d99a3bb396390"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3d7b8e6db2e8a963bc0c3be39b591fa153dc0add6c11f972de3983fe4cf1dd4a"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7f75fe58cd17375251466ca152e55cb501104ed27d5d98c5f44d5371bc15fd3"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "brooom"
  desc "Sweep disk clutter left behind by AI-assisted development."
  homepage "https://github.com/Tobias-Braun/brooom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brooom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brooom"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The short command br is not installed, because another tool (such as
    broot) may already use it. If br is free on your system, add it with:
      ln -s "$(brew --prefix)/bin/brooom" "$(brew --prefix)/bin/br"
  EOS
end
