# This file was generated by GoReleaser. DO NOT EDIT.
cask "brooom" do
  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "80b4592d20c07e4a2f1ffaeb9c45ff07f09a8bd7dcfe749909bf0391455402b5"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58d4660157fbaa9c5289185199790de09355d887eed2da5275a692b2b01d0372"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8ef655452070f29651d3dc873bce0a1fc4b5cef20aac5fc3c097eb3bac18cb22"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "862b56f9fb1e0628c828a00413d7907203191f0a638b3956861f674fc952daf9"
      url "https://github.com/Tobias-Braun/brooom/releases/download/v#{version}/brooom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "brooom"
  desc "Sweep disk clutter left behind by AI-assisted development."
  homepage "https://github.com/Tobias-Braun/brooom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brooom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brooom"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The short command br is not installed, because another tool (such as
    broot) may already use it. If br is free on your system, add it with:
      ln -s "$(brew --prefix)/bin/brooom" "$(brew --prefix)/bin/br"
  EOS
end
